# Generated by Django 4.1.3 on 2022-11-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=20)),
            ],
        ),
    ]
